//! Instantiate the compiled module a generated Dart wrapper carries.
//!
//! A generated `.slint.dart` embeds the whole `.slint` graph as one gzip+base64
//! blob — see `codegen/src/bundle.rs`, which produces it at generate time —
//! with imports rewritten to a virtual root and images inlined. `load()` hands
//! that blob to [`instantiate`], which compiles it through the interpreter once
//! per process, from memory, and then creates instances. Nothing reads `.slint`
//! from disk, so the source need not ship with the application.

use std::collections::HashMap;
use std::hash::{Hash, Hasher};
use std::path::PathBuf;
use std::rc::Rc;

use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use slint_interpreter::{CompilationResult, Compiler, ComponentDefinition, ComponentInstance};

/// Must match `codegen::bundle::MODULE_VERSION`; a wrapper generated by another
/// version of the tool is rejected rather than misread.
const MODULE_VERSION: u32 = 1;

thread_local! {
    static MODULES: std::cell::RefCell<HashMap<u64, CompilationResult>> =
        std::cell::RefCell::new(HashMap::new());
}

/// Compile [blob] if needed and instantiate [component], or the last exported
/// component when [component] is empty.
pub(crate) fn instantiate(
    blob: &str,
    component: Option<&str>,
) -> Result<ComponentInstance, String> {
    let definition = definition(blob, component)?;
    definition.create().map_err(|error| error.to_string())
}

fn definition(blob: &str, component: Option<&str>) -> Result<ComponentDefinition, String> {
    let hash = blob_hash(blob);
    MODULES.with(|modules| {
        let mut modules = modules.borrow_mut();
        if !modules.contains_key(&hash) {
            modules.insert(hash, compile_blob(blob)?);
        }
        pick_component(&modules[&hash], component)
    })
}

fn compile_blob(blob: &str) -> Result<CompilationResult, String> {
    let module = decode_module(blob)?;
    let version = module.get("v").and_then(|value| value.as_u64()).unwrap_or(0);
    if version != MODULE_VERSION as u64 {
        return Err(format!("unsupported compiled Slint module version {version}"));
    }
    let main = module
        .get("main")
        .and_then(|value| value.as_str())
        .ok_or_else(|| "compiled module is missing main".to_string())?
        .to_string();
    let files = module
        .get("files")
        .and_then(|value| value.as_object())
        .ok_or_else(|| "compiled module is missing files".to_string())?
        .iter()
        .map(|(path, source)| {
            source
                .as_str()
                .map(|source| (normalize_key(path), source.to_string()))
                .ok_or_else(|| format!("compiled module file {path} is not a string"))
        })
        .collect::<Result<HashMap<_, _>, _>>()?;
    let main_source = files
        .get(&normalize_key(&main))
        .cloned()
        .ok_or_else(|| "compiled module is missing its main file".to_string())?;
    let files = Rc::new(files);

    let mut compiler = Compiler::default();
    if let Some(style) =
        module.get("style").and_then(|value| value.as_str()).filter(|s| !s.is_empty())
    {
        compiler.set_style(style.to_string());
    }
    let loaded = files.clone();
    compiler.set_file_loader(move |path| {
        let requested = normalize_key(&path.to_string_lossy());
        let loaded = loaded.clone();
        Box::pin(async move { lookup_file(&loaded, &requested).map(Ok) })
    });

    let result = spin_on::spin_on(compiler.build_from_source(main_source, PathBuf::from(main)));
    if result.has_errors() {
        let messages = result
            .diagnostics()
            .map(|diagnostic| diagnostic.to_string())
            .collect::<Vec<_>>()
            .join("\n");
        return Err(messages);
    }
    Ok(result)
}

fn pick_component(
    result: &CompilationResult,
    component: Option<&str>,
) -> Result<ComponentDefinition, String> {
    match component.filter(|name| !name.is_empty()) {
        Some(name) => result.component(name).ok_or_else(|| {
            let names = result.component_names().collect::<Vec<_>>().join(", ");
            format!("no component named {name:?}; the module exports [{names}]")
        }),
        None => result
            .components()
            .last()
            .ok_or_else(|| "the compiled module exports no instantiable component".into()),
    }
}

pub(crate) fn decode_module(blob: &str) -> Result<serde_json::Value, String> {
    let compressed = STANDARD.decode(blob.trim()).map_err(|error| error.to_string())?;
    let json = flate2::read::GzDecoder::new(compressed.as_slice());
    serde_json::from_reader(json).map_err(|error| error.to_string())
}

fn blob_hash(blob: &str) -> u64 {
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    blob.hash(&mut hasher);
    hasher.finish()
}

fn normalize_key(path: &str) -> String {
    path.replace('\\', "/")
}

fn lookup_file<'a>(files: &'a HashMap<String, String>, requested: &str) -> Option<String> {
    if let Some(source) = files.get(requested) {
        return Some(source.clone());
    }
    files.iter().find_map(|(path, source)| {
        (requested.ends_with(path) || path.ends_with(requested)).then(|| source.clone())
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;
    use std::io::Write;

    /// The encoder lives in `codegen`, which this crate deliberately does not
    /// depend on, so the tests write the blob themselves. That also pins the
    /// wire format: if the two halves drift, these stop compiling a module the
    /// bundler still produces.
    fn encode_files(main: &str, files: BTreeMap<&str, &str>) -> String {
        let json = serde_json::json!({
            "v": MODULE_VERSION,
            "main": main,
            "files": files,
        });
        let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
        encoder.write_all(&serde_json::to_vec(&json).unwrap()).unwrap();
        STANDARD.encode(encoder.finish().unwrap())
    }

    #[test]
    fn a_bundled_import_compiles_without_touching_the_filesystem() {
        let blob = encode_files(
            "/slint-aot/app.slint",
            BTreeMap::from([
                (
                    "/slint-aot/app.slint",
                    r#"import { Shared } from "/slint-aot/shared.slint";
                    export component App inherits Shared { }"#,
                ),
                (
                    "/slint-aot/shared.slint",
                    "export component Shared { in-out property <int> n: 3; }",
                ),
            ]),
        );
        let result = compile_blob(&blob).unwrap();
        assert!(result.component("App").is_some());
    }

    #[test]
    fn a_relative_import_resolves_under_the_virtual_root() {
        let blob = encode_files(
            "/slint-aot/app.slint",
            BTreeMap::from([
                (
                    "/slint-aot/app.slint",
                    r#"import { Shared } from "shared.slint";
                    export component App inherits Shared { }"#,
                ),
                (
                    "/slint-aot/shared.slint",
                    "export component Shared { in-out property <int> n: 4; }",
                ),
            ]),
        );
        let result = compile_blob(&blob).unwrap();
        assert!(result.component("App").is_some());
    }
}
