include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/ui/*.slint.dart
    - lib/ui/**/*.slint.dart
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
